name: Reusable Workflow to set due date to closed issue

on:
  issues:
    types: [closed]

jobs:
  do-it:
    uses: o-futuro-ja-comecou/github-actions-reutilizaveis/.github/workflows/set_due_date_to_orgs_closed_issue_reusable.yml@v1.0
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ACCOUNT: ${{ secrets.ACCOUNT }}
        PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
